spring:
  application:
    name: eureka

server:
  port: 8761

eureka:
  server:
    enableSelfPreservation: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: 127.0.0.1
    preferIpAddress: true