spring:
  application:
    name: pvd-service

server:
  port: 2300

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.60.87:8761/eureka/,http://192.168.60.87:8762/eureka/
  instance:
    preferIpAddress: true