server: 
  port: 8888

spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dlutcoco/spring-cloud-demo
          searchPaths: conf-repo

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/